In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
y = np.array([2., 3.9, 6.1])

In [4]:
x.mean

<function ndarray.mean>

In [5]:
x.mean()

2.0

In [6]:
y.mean()

4.0

In [7]:
xc = x - x.mean()

In [8]:
yc = y - y.mean()

In [9]:
xc

array([-1.,  0.,  1.])

In [10]:
yc

array([-2. , -0.1,  2.1])

In [11]:
xc*xc

array([1., 0., 1.])

In [12]:
xx = xc*xc

In [13]:
xy = xc*yc

In [14]:
xx.sum()

2.0

In [15]:
xy.sum()

4.1

In [16]:
xy.sum() / xx.sum()

2.05